name: Build and push image (Dodo)
on:
  workflow_dispatch:
  push:
    branches:
      - dodo

jobs:
  push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get short SHA
        run: echo "sha7=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: "Dockerfile.standalone"
          tags: >
            ghcr.io/${{ github.repository }}:latest,
            ghcr.io/${{ github.repository }}:${{ env.sha7 }}
          platforms: |
            linux/amd64
      - name: Output image tags
        run: |
          echo "**Public docker image:** ghcr.io/${{ github.repository }}:${{ env.sha7 }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit message:** ${{ github.event.head_commit.message }}" >> $GITHUB_STEP_SUMMARY
